import 'dart:convert';

/// Represents a simple visual rule constructed by the user for the JS Crypto Hook.
class CryptoRule {
  /// The algorithm being targeted (e.g. 'AES/CBC/PKCS5Padding'). Can be empty to match all.
  final String algorithm;

  /// The MD5 Fingerprint generated by the lower level Crypto hook indicating the exact caller.
  final String fingerprint;

  /// Whether the target is the Input (encrypting data/pre-decryption payload) or Output (decrypted data/ciphertext).
  final bool isInput;

  /// The string replacing the original data. If this is empty, no replacement occurs.
  final String replaceWith;

  /// Unique identifier for the rule, used to preserve user modifications in the JS body.
  final String id;

  CryptoRule({
    String? id,
    this.algorithm = '',
    this.fingerprint = '',
    this.isInput = false,
    this.replaceWith = '',
  }) : id = id ?? DateTime.now().millisecondsSinceEpoch.toString();

  /// Generate a valid Javascript syntax IF block logic
  String generateJavascriptBlock() {
    List<String> conditions = [];
    if (algorithm.isNotEmpty) {
      conditions.add("context.algorithm === '$algorithm'");
    }
    if (fingerprint.isNotEmpty) {
      conditions.add("context.fingerprint === '$fingerprint'");
    }
    
    // Convert boolean mapped to 'isInput' property to a boolean js expression
    if (isInput) {
      conditions.add("isInput === true");
    } else {
      conditions.add("isInput === false");
    }

    final conditionExpression = conditions.isEmpty ? "true" : conditions.join(' && ');
    
    // Auto-escape the string
    final safeReplacementString = jsonEncode(replaceWith);

    return """
// --- RULE START: $id ---
if ($conditionExpression) {
  // VISUAL_REPLACE_START
  console.log("Visual Rule Hit! Replacing data for fingerprint: " + context.fingerprint);
  let result = JxCrypto.replaceWithString($safeReplacementString);
  // VISUAL_REPLACE_END

  // 👇 --- 请在此下方编写你的自定义逻辑/Write your custom logic below here --- 👇
  

  return result;
}
// --- RULE END: $id ---
""";
  }

  CryptoRule copyWith({
    String? algorithm,
    String? fingerprint,
    bool? isInput,
    String? replaceWith,
  }) {
    return CryptoRule(
      id: this.id,
      algorithm: algorithm ?? this.algorithm,
      fingerprint: fingerprint ?? this.fingerprint,
      isInput: isInput ?? this.isInput,
      replaceWith: replaceWith ?? this.replaceWith,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'algorithm': algorithm,
      'fingerprint': fingerprint,
      'isInput': isInput,
      'replaceWith': replaceWith,
      'id': id,
    };
  }

  factory CryptoRule.fromJson(Map<String, dynamic> json) {
    return CryptoRule(
      algorithm: json['algorithm'] ?? '',
      fingerprint: json['fingerprint'] ?? '',
      isInput: json['isInput'] ?? false,
      replaceWith: json['replaceWith'] ?? '',
      id: json['id'],
    );
  }
}

